{% set name = "dpdispatcher" %}
{% set version = environ.get('GIT_DESCRIBE_TAG').lstrip('v') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/deepmodeling/dpdispatcher
  # git_rev: {{ version }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - git
  host:
    - git
    - python >=3.7.4
    - pip
    - setuptools_scm
    - dargs >=0.5.0
    - paramiko
    - requests
    - tqdm >=4.9.0

  run:
    - python >=3.7.4
    - dargs >=0.5.0
    - paramiko
    - pyyaml
    - requests
    - tomli >=1.1.0  # [py<311]
    - tqdm >=4.9.0

test:
  imports:
    - dpdispatcher

about:
  home: https://github.com/deepmodeling/dpdispatcher
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://github.com/deepmodeling/dpdispatcher
  dev_url: https://github.com/deepmodeling/dpdispatcher

extra:
  recipe-maintainers:
    - felix5572
