on: [push, pull_request]
name: Release to pypi
jobs:
  release-to-pypi:
    uses: deepmodeling/workflows/.github/workflows/release-to-pypi.yml@main
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
