name: Test Bohirum

on:
  push:
  pull_request:
    types:
      - "labeled"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: bohirum
    if: github.repository_owner == 'deepmodeling' && github.event.label.name == 'Test Bohirum' || github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: pip install .[bohirum] coverage
    - name: Test
      run: coverage run --source=./dpdispatcher -m unittest -v tests/test_run_submission_bohirum.py && coverage report
      env:
        DPDISPATCHER_TEST: bohirum
        BOHRIUM_EMAIL: ${{ secrets.BOHRIUM_EMAIL }}
        BOHRIUM_PASSWORD: ${{ secrets.BOHRIUM_PASSWORD }}
        BOHRIUM_PROJECT_ID: ${{ secrets.BOHRIUM_PROJECT_ID }}
        BOHRIUM_ACCESS_KEY: ${{ secrets.BOHRIUM_ACCESS_KEY }}
    - uses: codecov/codecov-action@v3
