'on':
  push:
    branches-ignore:
      - 'copilot/**'
      - 'dependabot/**'
      - 'pre-commit-ci-update-config'
  pull_request:
name: ty
jobs:
  ty:
    # for compatibility of rulesets
    name: pyright
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v7
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v7
    - name: Run ty
      run: uvx --from ty==0.0.17 --with .[cloudserver,gui] --with tomli ty check
